version: 2

# Check for updates to Maven dependencies
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    all:
      patterns:
      - "*"

# Check for updates to GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
